"use client"
// globals.css
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [dark,setDark]=useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
       <div className={`${dark?"text-white bg-black":"text-black bg-white"}`}>
       <div className="w-[90vw] mx-auto py-4">
          <Navbar dark={dark} setDark={setDark}/>
        </div>
        {children}
       </div>
      </body>
    </html>
  );
}
