"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import {ThemeProvider,useThemeContext} from "./lib/provider/ThemeContext"

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <RootContent>{children}</RootContent>
    </ThemeProvider>
  );
}

function RootContent({ children }) {
  const {dark}=useThemeContext();
  console.log(dark)
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={`${dark?"text-white bg-black":"text-black bg-white"} overflow-x-hidden min-h-screen`}>
          <div className="w-[90vw] mx-auto py-4">
            <Navbar />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}

